### ISSUE TITLE
Is exclusion support needed?

### ISSUE THREAD

**Issue by wtjones** [mtkennerly/ludusavi-manifest#1]
[Stellaris](https://www.pcgamingwiki.com/wiki/Stellaris#Game_data) is listed as having both save and config under $XDG_DATA_HOME/Paradox Interactive/Stellaris/.

In reality: 
- Save are really under $XDG_DATA_HOME/Paradox Interactive/Stellaris/save games
- Settings are sort of littered at the root of and under this folder.

For this reason, pulling the entire folder makes sense, however it will also grab:
- shadercache
- .launcher-cache
- logs

Potential solutions:
- Modify the wiki to fix the save folder and somehow list out all the settings files and mod folder (Does the wiki support this? I wasn't sure)
- Add an exclusion pattern in this manifest to filter out logs etc
- Do nothing because the total size is only 16 MB.

This isn't really a big deal, but I thought I would bring it up since it may be a bigger issue with other titles.

**Comment by mtkennerly** [comment]
I feel better about explicitly including files than excluding them. If you have an exclusion list, then you'll have a problem as soon as the devs add any new file or folder. Of course, the opposite can happen with an inclusion list (you miss out on new files that you might want), but I think it's safer to opt in to files rather than opt out.

The `Game data/config` and `Game data/saves` wiki templates are variadic, so for example this code:

```
===Configuration file(s) location===
{{Game data|
{{Game data/config|Linux|{{P|xdgdatahome}}/Paradox Interactive/Stellaris/first|{{P|xdgdatahome}}/Paradox Interactive/Stellaris/second|{{P|xdgdatahome}}/Paradox Interactive/Stellaris/third}}
}}
{{XDG|true}}
```

Produces:

> ![image](https://user-images.githubusercontent.com/4934192/87074367-bfa62200-c1ec-11ea-8457-1a9694d00c50.png)

I think that would be the ideal way to handle cases like this, so that the wiki becomes even more accurate.

I *believe* the import script already handles this syntax, because I think I saw some cases where it worked, but to be honest I'm not sure why it works since I didn't specifically code for it 🙃

**Comment by wtjones** [comment]
Ah, I was wondering how to have multiple entries. I think this should work for most cases. Thanks!
