### ISSUE TITLE
<base>/<path-to-game> not detected for Oddworld: Soulstorm Enhanced Edition

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi-manifest#13]
[Oddworld: Soulstorm Enhanced Edition](https://www.pcgamingwiki.com/wiki/Oddworld:_Soulstorm_Enhanced_Edition) on PCGW lists "\<path-to-game\>\Settings" (`{{p|game}}\Settings`) as a _config path_, but that path isn't shown in my Ludusavi games list. The only files listed that I see are those that match the first of the _game data locations_ "%USERPROFILE%\AppData\LocalLow\Oddworld Inhabitants Inc\Oddworld_ Soulstorm".

Is this something to do with the game entry being called "Oddworld: Soulstorm Enhanced Edition" but the installation path on my system only containing "Oddworld - Soulstorm"? I did actually manually move the entire game's installation folder at one point to make room for more EGS downloads so maybe that has something to do with it also. Seems the game was rebranded to " Enhanced Edition" too.

If I make a custom game entry in Ludusavi and specify the exact path to \Settings, it finds it no problem.

How does Ludusavi detect the "\<path-to-game\>" i.e. "\<base\>" in Ludusavi's terms?

Thanks.

**Comment by mtkennerly** [comment]
Ludusavi looks for a folder in the root that either matches the game title or one of its `installDir` entries (sourced from Steam) in the manifest. If it can't find an exact match, it will also check for something that's "close enough", but this has its limits. The "enhanced edition" is throwing it off because there wasn't an `installDir` in the manifest.

I ran a refresh on the Steam metadata for the game, and it came up with an `installDir` this time. I'm not sure why that was missing; maybe the original check happened before the game came out. I'll need to look into making sure the Steam metadata updates periodically, since right now it happens once per game.

I've updated the manifest, which now includes `Oddworld Soulstorm` as the `installDir`. Since your folder has a hyphen, this should be recognized by the "close enough" logic now.

**Comment by redactedscribe** [comment]
> I've updated the manifest, which now includes `Oddworld Soulstorm` as the `installDir`. Since your folder has a hyphen, this should be recognized by the "close enough" logic now.

I've restarted Ludusavi twice and let it sit a moment to be sure that the manifest has been downloaded. I've checked my manifest.yaml and it now contains:

```yaml
  installDir:
    Oddworld Soulstorm: {}
```

But still, the \Settings folder isn't being matched, i.e. "Oddworld - Soulstorm" isn't close enough I think.

Are you sure it should be "close enough", or am I doing something wrong?
