### ISSUE TITLE
What does the manifest update process look like moving forward?

### ISSUE THREAD

**Issue by sharkusmanch** [mtkennerly/ludusavi-manifest#2]
How do you envision the master manifest being updated moving forward? Maybe some automated job that automatically updates the cache and manifest.yaml on a periodic interval?

**Comment by mtkennerly** [comment]
I'd like to use a [scheduled GitHub Action](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule) to run an update every few days. Right now, I'm working on an enhancement to the importer script to use the wiki's Recent Changes API, since I don't want to waste their bandwidth by hitting all 40,000+ pages every time 😅 Once that's done, I'll still run it manually for a bit, just so I can inspect the output and do some sanity checks, but once I'm confident that it's working consistently, then I would set up the scheduled task and let it commit automatically.

**Comment by mtkennerly** [comment]
FYI, the Recent Changes integration is done, and I've updated the manifest with all wiki pages edited in the last 30 days (since I created the repo on June 20).

**Comment by mtkennerly** [comment]
This is now 100% automated, starting with 76e7c14d21a8225831814ef6a56ef9929922c7fe \:D It'll run every day at midnight UTC.

![image](https://user-images.githubusercontent.com/4934192/91242273-fe4c5900-e714-11ea-82e0-006b84c622eb.png)
