### ISSUE TITLE
Medal of Honor - Allied Assault Warchest

### ISSUE THREAD

**Issue by Patrxgt** [mtkennerly/ludusavi-manifest#25]
Ludusavi tried to backup whole 'main', mainta' and 'maintt' folders, which are full of game archives, instead of backing up only 'save' and 'configs' folders, which are inside of main folders.

**Comment by mtkennerly** [comment]
That's coming from this section on PCGamingWiki: https://www.pcgamingwiki.com/wiki/Medal_of_Honor:_Allied_Assault#Game_data

Could you confirm if this is all correct?

* `<path-to-game>\main\newconfig.cfg`
* `<path-to-game>\main\configs\unnamedsoldier.cfg`
* `<path-to-game>\maintt\newconfig.cfg`
* `<path-to-game>\maintt\configs\unnamedsoldier.cfg`
* `<path-to-game>\mainta\newconfig.cfg`
* `<path-to-game>\mainta\configs\unnamedsoldier.cfg`

**Comment by Patrxgt** [comment]
Those are just config files. There should be also:
-<path-to-game>\main\saves
-<path-to-game>\mainta\save
-<path-to-game>\maintt\save

**Comment by mtkennerly** [comment]
Gotcha, those are already covered in the `Save game data location` section, so just needed to confirm the config paths. I've [updated the `Configuration file(s) location` section](https://www.pcgamingwiki.com/w/index.php?title=Medal_of_Honor:_Allied_Assault&diff=1401341&oldid=1395633) on the wiki, so that should resolve the issue after the next manifest update.
