### ISSUE TITLE
Support for Bolded / Italic Parentheses in Game Paths Used for Notes

### ISSUE THREAD

**Issue by RuiNtD** [mtkennerly/ludusavi-manifest#26]
Hello. I tried to add the save location for Minecraft Bedrock **Preview** to [the PCGW page](https://www.pcgamingwiki.com/wiki/Minecraft:_Bedrock_Edition) for use in Ludusavi. I can see it was added to `wiki-game-cache.yml` in 9a0ad33a25ab4f5d212f57a26bf65bd1efadc201, but not to the manifest. Did I do something wrong? Thanks.

**Comment by RuiNtD** [comment]
I was actually told by the Discord to do that. There are actually multiple articles that do that, including [Cave Story+](https://www.pcgamingwiki.com/wiki/Cave_Story%2B). Wouldn’t it make more sense for the parser to handle that?

**Comment by RuiNtD** [comment]
Well, technically I was told to use italics `''(Preview)''` by the Discord, but that Cave Story+ article uses bold `'''(Preview)'''`, so that’s what I did. I’m asking in the Discord now about what is preferred and if it can be added to the editing guide.

**Comment by RuiNtD** [comment]
![IMG_1015](https://github.com/mtkennerly/ludusavi-manifest/assets/1149870/ea452b43-04ff-441e-92b5-ef9859b38deb)

Sounds like they have no plans to standardize bold or italic parentheses?

**Comment by DandelionSprout** [comment]
I'd say that a bigger concern in that regard would be pages that use `{{notes|}}` in their paths, e.g. https://www.pcgamingwiki.com/wiki/Baldur%27s_Gate:_Dark_Alliance_II; which I presume would take a bit more effort to simply remove in scripts.

**Comment by mtkennerly** [comment]
Surprisingly, those aren't too bad because I know a `{{notes|}}` will never be part of the path itself, but bolded text could potentially be part of the path. At least, it could in theory, but if that's not the case in practice, then I can just skip all bold/italic text altogether.

This is the relevant part of how I'm handling paths:

https://github.com/mtkennerly/ludusavi-manifest/blob/15a5a16aed9ffb84d328a8577a3404d919073f7b/src/wiki.ts#L631-L635

For example, node type `case "template"` followed by template name `case "file"` means it's handling `{{file|...}}`. It just skips unhandled templates and uses what's left of the path, but if it encounters an unhandled non-template element, then it discards the whole path.

**Comment by mtkennerly** [comment]
I just updated it to ignore bold/italic (2b76438e55c4240eabbcd89e386cbf2877318dff), and thanks to some of the recent cleanup by @DandelionSprout on the wiki, it looks like Minecraft: Bedrock Edition is the *only* game affected by the change 🎉
