### ISSUE TITLE
Exclusion support for path with patterns

### ISSUE THREAD

**Issue by starsep** [mtkennerly/ludusavi-manifest#4]
I am facing similar issue to #1 
I noticed that backup of [Metro 2033 Redux](https://www.pcgamingwiki.com/wiki/Metro_2033_Redux) contains 2033 directory with video files (641MB):
`intro.ogv legal.ogv  outro_bad.ogv  outro_good.ogv`

Full path is `Metro 2033 Redux/drive-F/Steam/steamapps/common/Metro 2033 Redux/2033`.
2033 matches `<user-id>` pattern.
Is there a way to exclude this directory?

**Comment by mtkennerly** [comment]
Hi! Yes, that's possible. You can click the edit button next to the game (![image](https://user-images.githubusercontent.com/4934192/100788311-e7d42e80-33e2-11eb-93e6-4b2513f2f6a6.png)) to create a custom entry for it, and then modify the file paths or add new ones so that it doesn't include the video directory or any of its parent directories.

I'm not sure how the saves for Metro 2033 Redux look exactly, but here are some examples of what you might end up with:

* Example 1, if the 2033 folder includes videos and also save files. `*.sav` means any file that ends with the `.sav` extension:
  * `F:/Steam/steamapps/common/Metro 2033 Redux/2033/*.sav`
* Example 2, if the 2033 folder includes subfolders where the actual saves are located:
  * `F:/Steam/steamapps/common/Metro 2033 Redux/2033/Save Files`

It would be great to add the same detail to PCGamingWiki so everyone can benefit from it, but that's not required.

**Comment by starsep** [comment]
Video files are in `Metro 2033 Redux/drive-F/Steam/steamapps/common/Metro 2033 Redux/2033`
Save files are in `Metro 2033 Redux/drive-F/Steam/steamapps/common/Metro 2033 Redux/<11 characters user id>`
I suppose there is no way to exclude that by editing PCGamingWiki, right?
I will try custom entry.
Thanks for the answer!

**Comment by darklinkpower** [comment]
This is basically the same as https://github.com/mtkennerly/ludusavi/issues/39

**Comment by darklinkpower** [comment]
The problem is that some games may not only use alphanumeric characters for the user id so it may be difficult to have an automatic way.
