### ISSUE TITLE
Economic Conquest configuration backs up everything in <home>/Saved Games/

### ISSUE THREAD

**Issue by rogeriodomingos** [mtkennerly/ludusavi-manifest#40]
This includes data from other games. The [PCGamingWiki page](https://www.pcgamingwiki.com/wiki/Economic_Conquest) doesn't list that path so I'm not sure where it's coming from.

**Comment by mtkennerly** [comment]
Hi! I just fixed this a few minutes ago, but thank you for reporting it. You can use the refresh button on the "other" screen to get the latest manifest with the fix.

I'm in the process of I'm re-scraping Steam metadata so that the manifest can use Steam Cloud paths only in cases where PCGamingWiki doesn't have any save info. Unfortunately, some games' Steam Cloud metadata is not well defined, so I'm adjusting the filters as I go to catch cases like this.

Please let me know if you see any other issues :)
