### ISSUE TITLE
Custom Manifest with game recognition

### ISSUE THREAD

**Issue by hvmzx** [mtkennerly/ludusavi-manifest#50]
Working on a custom manifest for games (added to steam as non-steam games) that wouldn't be listed in PCGamingWiki (using steamOS).

Here is an example : 

```
---
"Non-Steam":
  files:
    "<root>/**/pfx/drive_c/users/Public/Documents":
      tags:
        - save
      when:
        - os: linux
```

With this, I correctly get all the games /Documents folder, however under Ludusavi they all show under "Non-Steam" game which is to be expected but it would be dope if that was handled to show the different names of games where that folder has been found.

Here are 2 propositions for this : 

- the ** would be recognised and the title of that folder, would be used as the game title under Ludusavi
- get the title from steam that matches the ** folder as each entry in steam has an associated folder

Would love to hear what you think about this, as it would make using custom games more automated.

PS: the names of the shortcut in steam matches PCGamingWiki, if that could help

Thanks already for the great work you've done on Ludusavi !

**Comment by mtkennerly** [comment]
Hi! This is an interesting use case.

The first challenge here is how to define the path using the standard manifest `<placeholders>` so that Ludusavi can use its own logic to help find the right folder for each game. The second challenge is how to add the same path pattern for many games.

### Using placeholders
Right now:

* On Linux, for games with a Steam app ID in the manifest, Ludusavi will check in each Steam root's `compatdata` based on that game's app ID. It can translate most placeholders, such as `<winPublic>` -> `steamapps/compatdata/{id}/pfx/drive_c/users/Public`: https://github.com/mtkennerly/ludusavi/blob/26933e5e9e235bccf7112db7247e685b79e9bba5/src/scan.rs#L289
* For Steam shortcuts (non-Steam games added to Steam), Ludusavi defines `<base>` as the shortcut's starting folder, but doesn't handle any other placeholders: https://github.com/mtkennerly/ludusavi/blob/26933e5e9e235bccf7112db7247e685b79e9bba5/src/scan.rs#L263
  * Side note: Ludusavi only considers Steam shortcuts whose name matches a manifest entry. If the name doesn't match, then Ludusavi ignores that shortcut.

Each Steam shortcut is assigned an app ID, but Ludusavi does not include that ID in the `compatdata` handling above. If it did, then you could write `<winPublic>/Documents` in your manifest, and Ludusavi would check the correct compatdata for each Steam shortcut. However, Ludusavi doesn't enforce the `when` constraints, so this would also trigger on Windows for the regular `<winPublic>` folder, which isn't good.

If we added a new placeholder for the Steam app ID, then you could write `<root>/compatdata/<storeGameId>/pfx/drive_c/users/Public/Documents` without incorrectly triggering for `C:\Users\Public` on Windows systems. I think this is probably the best approach.

### Adding a path to many games
I think this doesn't quite align with the design goals of the manifest format, but let's think about how it could work anyway.

Ideally, however we express this, it shouldn't cause too much trouble for an older version of Ludusavi that doesn't understand it. One option could be introducing a reserved name:

```yaml
"<ludusavi:all>":
  files:
    "<root>/compatdata/<storeGameId>/pfx/drive_c/users/Public/Documents": {}
```

Existing versions of Ludusavi would treat it as a regular game, but as long as the paths use game-specific placeholders like `<game>` and `<storeGameId>`, it just won't find anything. New versions of Ludusavi could give `<ludusavi:all>` special treatment. That special treatment would probably need to include enforcing the `when` constraints. The constraints aren't as important for explicit paths defined on each game, since there's a low risk of collision, but for these global paths, collisions and wrong-OS checks would be a bigger issue.

Now, that being said - adding a new `<storeGameId>` placeholder is fairly easy, but adding special handling for a reserved game name is much more complex. Before introducing that, I would like to know if there are more use cases for this feature where a path truly needs to be added globally, to weigh the pros and cons of implementing it.

> PS: the names of the shortcut in steam matches PCGamingWiki, if that could help

It does! That means you could set up a GitHub workflow that runs on some schedule (e.g., daily/weekly), gets all the game names from the primary manifest, and generates the same entry for each of them. I'm not sure how familiar you are with GitHub workflows, but the import workflow in this repo has an example of a schedule and auto-committing changed files: https://github.com/mtkennerly/ludusavi-manifest/blob/master/.github/workflows/import.yaml

You could also use anchors to limit the duplication:

```yaml
"": &template
  files:
    "<root>/compatdata/<storeGameId>/pfx/drive_c/users/Public/Documents":
      tags:
        - save
      when:
        - os: linux

Game from manifest 1: *template
Game from manifest 2: *template
```

I just tested this with a local manifest, and it seems to work correctly. Because `""` is an empty string, that entry is ignored and won't show up in the scan results in Ludusavi itself, but it still works as an anchor to populate the other entries.

**Comment by mtkennerly** [comment]
I've implemented the support for `<storeGameId>` in Ludusavi: https://github.com/mtkennerly/ludusavi/commit/14e68b035875015562a9d0a0f8703d266afca8ab , so that will be available in the next release (although I'm not sure when that will be yet).

**Comment by hvmzx** [comment]
Perfect, thank you for implementing it, looking forward to testing it !

**Comment by mtkennerly** [comment]
Ludusavi 0.26.0 is now available :D https://github.com/mtkennerly/ludusavi/releases/tag/v0.26.0

**Comment by hvmzx** [comment]
I've tried the following yaml but it doesn't seem to find any games unfortunately, i have the steam root "/home/deck/.steam/steam/steamapps" : 

```
---
"": &template
  files:
    "<root>/compatdata/<storeGameId>/pfx/drive_c/users/Public/Documents":
      tags:
        - save
    "<root>/compatdata/<storeGameId>/pfx/drive_c/users/steamuser/Documents":
      tags:
        - save
    "<root>/compatdata/<storeGameId>/pfx/drive_c/users/steamuser/Appdata":
      tags:
        - save
    "<root>/compatdata/<storeGameId>/pfx/drive_c/users/steamuser/Saved Games":
      tags:
        - save
      when:
        - os: linux
```

**Comment by mtkennerly** [comment]
That just defines a template, but like I mentioned, you would still need one line per game to use the template, as in:

```
Game from manifest 1: *template
Game from manifest 2: *template
```

You could generate that with a fairly simple script that clones the primary manifest, parses the YAML, and generates one line per title.

**Comment by hvmzx** [comment]
> That just defines a template, but like I mentioned, you would still need one line per game to use the template, as in:
> 
> ```
> Game from manifest 1: *template
> Game from manifest 2: *template
> ```
> 
> You could generate that with a fairly simple script that clones the primary manifest, parses the YAML, and generates one line per title. If you'd like help with writing it, let me know.

So this means that the manifest needs to be updated every time a new game is added ?

I thought a nice way to implement it was just with that for each prefix folder, ludisavi pulls the title of that game from Steam and instead of the root folder named 21409418 for example, ludisavi creates a folder named after its title.

**Comment by mtkennerly** [comment]
> So this means that the manifest needs to be updated every time a new game is added ?

Yes, but you can set up a [GitHub workflow](https://docs.github.com/en/actions/writing-workflows) that automatically runs on a schedule so you don't have to think about it. For example, this would do once every 24 hours:

```yaml
on:
  schedule:
    - cron: '0 0 * * *'
```

The primary manifest itself uses a 6-hour schedule right now:

https://github.com/mtkennerly/ludusavi-manifest/blob/30e56e32e7874ac3319495d90362967a35e5da00/.github/workflows/import.yaml#L1C1-L4

> I thought a nice way to implement it was just with that for each prefix folder, ludisavi pulls the title of that game from Steam and instead of the root folder named 21409418 for example, ludisavi creates a folder named after its title.

That's potentially possible, but I'm hesitant to add that to the manifest format right now, since the intention behind the format is really to identify the specific paths that each game uses, rather than indiscriminately adding a set of paths to every game. For now, until we identify some more use cases for something like this, I'd recommend the generation-via-script option since it doesn't require a change to the manifest specification.

**Comment by hvmzx** [comment]
> Yes, but you can set up a [GitHub workflow](https://docs.github.com/en/actions/writing-workflows) that automatically runs on a schedule so you don't have to think about it. For example, this would do once every 24 hours:

The only part that needs to be automatised is this one, but I hardly see how that can be automatised:

```
Game from manifest 1: *template
Game from manifest 2: *template

```

> That's potentially possible, but I'm hesitant to add that to the manifest format right now

Thank you, I will look into it, glad you're listening to feedback about it.

**Comment by mtkennerly** [comment]
> The only part that needs to be automatised is this one, but I hardly see how that can be automatised:

Just sent you a PR: https://github.com/hvmzx/ludusavi-manifests/pull/1
