### ISSUE TITLE
XDG_CONFIG_HOME and wrong save location

### ISSUE THREAD

**Issue by nicolasnobelis** [mtkennerly/ludusavi-manifest#51]
I played `Shadow Tactics: Blades of the Shogun - Aiko's Choice` on Steam on Linux and Ludusavi does not find any saves for it.

In the manifest, the saves should be at:
`<xdgConfig>/.local/share/Daedalic Entertainment GmbH/Shadow Tactics Blades of the Shogun Aikos Choice/user/gameState_00`.
Same on PCGamingWiki: https://www.pcgamingwiki.com/wiki/Shadow_Tactics:_Blades_of_the_Shogun_-_Aiko%27s_Choice

On my local filesystem, there are in:
`~/.local/share/Daedalic\ Entertainment\ GmbH/Shadow\ Tactics\ Blades\ of\ the\ Shogun\ Aikos\ Choice/user/gameState_00`.

Looking at the documentation, `<xdgConfig>` is defined to `$XDG_CONFIG_HOME` which is not set on my system (Linux Mint LMDE 6).

Is it a prerequisite of Ludusavi to set this variable ?

Please note that, looking at the specs (https://specifications.freedesktop.org/basedir-spec/latest/#variables), if XDG_CONFIG_HOME is not set, `$HOME/.config` should be used instead. But it my case, it would not help because the saves are in `~/.local/share/` not `~/.config/local/share/.`

**Comment by nicolasnobelis** [comment]
Oh I saw this: https://github.com/mtkennerly/ludusavi/blob/1405ae7310859c8506e1859c45014ee9ab01aac9/CHANGELOG.md?plain=1#L297-L299

I installed ludusavi via flatpack so this is what may be happening. Should ludusavi test `~/` too ?

**Comment by mtkennerly** [comment]
Hi! I think, in this case, the wiki is simply incorrect. Instead of `$XDG_CONFIG_HOME/.local/share/...`, it should be `$XDG_DATA_HOME/...`, because `$XDG_DATA_HOME` defaults to `$HOME/.local/share`. I also confirmed this based on the metadata from the Steam API for this game.

I've [updated the wiki](https://www.pcgamingwiki.com/w/index.php?title=Shadow_Tactics:_Blades_of_the_Shogun_-_Aiko%27s_Choice&diff=1522261&oldid=1519480) and [the manifest](https://github.com/mtkennerly/ludusavi-manifest/commit/8047ded7c0bb50e7b6c21b20071c56b53254bf16), so this should work when you download the latest manifest :)

**Comment by nicolasnobelis** [comment]
Thanks, it worked !

Two questions for the future:
- If I update the wiki myself, will Ludusavi's Manifest be automatically updated ?
- How did you check the Steam API ?

**Comment by mtkennerly** [comment]
* Yes, it will. There's normally a script that runs every 6 hours to check the latest changes on the wiki. Unfortunately, the wiki recently made some anti-bot changes, so I've just been running it manually every 24~48 hours 😅 
* This repo [uses a Python library](https://github.com/mtkennerly/ludusavi-manifest/blob/master/scripts/get-steam-app-info.py) to get some info from Steam, then [caches that info](https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/refs/heads/master/data/steam-game-cache.yaml). Games with Steam Cloud support can define primary paths (typically for Windows) and override paths (typically for other OSes). There aren't any overrides for Aiko's Choice (1579380), but the main game (418240) does have one for Linux that says to use `LinuxXdgDataHome` instead of `WinAppDataLocal`:

  ```yaml
      - addPath: ""
        os: Linux
        osCompare: "="
        root: WinAppDataLocal
        useInstead: LinuxXdgDataHome
  ```

  You can also view that info on steamdb: https://steamdb.info/app/418240/ufs/

**Comment by nicolasnobelis** [comment]
Thanks a lot for your support !
