### ISSUE TITLE
Age of Empires III: Definitive Edition: Only configuration files are to be backed up

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi-manifest#7]
The [Age of Empires III: Definitive Edition PCGamingWiki article](https://www.pcgamingwiki.com/wiki/Age_of_Empires_III:_Definitive_Edition) has the [save game data locations](https://www.pcgamingwiki.com/wiki/Age_of_Empires_III:_Definitive_Edition#Save_game_data_location) defined but Ludusavi is only showing the [Configuration file(s) location](https://www.pcgamingwiki.com/wiki/Age_of_Empires_III:_Definitive_Edition#Configuration_file.28s.29_location) path in its UI. Data exists at both paths on my system.

Both the "Common" directory and the "<16 digit number>\Savegame" directory should be being checked but Ludusavi is ignoring the latter for some reason. Maybe the <16 digit number> part not being the literal path is causing the issue?

![lsaoede](https://user-images.githubusercontent.com/25013746/180325132-137e051b-7791-49ac-987a-454c94bcdabd.jpg)

I don't know what is the minimum data Ludusavi aims to back up, but the "<16 digit number>\" directory holds other possibly desirable content, such as mods and screenshots. Maybe these are assumed for the user to create custom manifests for? Or is this addressable via the wiki and Ludusavi would pick it up? I'm new to the program and the wiki so excuse my ignorance.

Thanks.

Ludusavi 0.10.0
Windows 11

**Comment by redactedscribe** [comment]
In comparison to GameSave Manager, it attempts to backup both the "<16 digit number>" directory as a whole (mods, screenshots, and all), and the "Common" directory.

**Comment by mtkennerly** [comment]
Thanks for reporting this. The issue was that the importer script ignored HTML(-like) tags (in this case, `<sup>16 digit number</sup>`). I originally ignored them because it's ambiguous whether they're used for formatting or information, as well as how much text is affected by the tag (because of unclosed tags), but I've tried implementing a simple heuristic that seems to get good results so far. The manifest is updated, so you should see the issue fixed when you next launch Ludusavi.

**Comment by redactedscribe** [comment]
Yep, it's picking up the <digits>\Savegame path now too thanks.
